version: "3.9"

services:
  devopsdb:
    image: rajubingi2664/dockerautodemo:db
    ports:
      - "3306:3306"

  application:
    image: rajubingi2664/dockerautodemo:app
    ports:
      - "2222:8080"

